### ISSUE TITLE
ImportError: No module named xkcd_password

### ISSUE THREAD

**Issue by durzo** [redacted/XKCD-password-generator#23] opened 2015-04-14 03:10 UTC
Ubuntu 14.04, installed via pip, cannot find the module.

Python 2.7

$ pip show xkcdpass
---
Name: xkcdpass
Version: 1.2.5
Location: /usr/local/lib/python2.7/dist-packages

code:
#!/usr/bin/python
import xkcdpass.xkcd_password as xp

output:
Traceback (most recent call last):
  File "./passgen.py", line 2, in <module>
    import xkcdpass.xkcd_password as xp
  File "/root/xkcdpass.py", line 2, in <module>
ImportError: No module named xkcd_password

strace shows its not even looking:
open("/root/xkcdpass.py", O_RDONLY)     = -1 ENOENT (No such file or directory)
open("/usr/local/lib/python2.7/dist-packages/python_etcd-0.3.2-py2.7.egg/xkcdpass.py", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/local/lib/python2.7/dist-packages/pyOpenSSL-0.14-py2.7.egg/xkcdpass.py", O_RDONLY) = -1 ENOTDIR (Not a directory)
open("/usr/local/lib/python2.7/dist-packages/cryptography-0.8.1-py2.7-linux-x86_64.egg/xkcdpass.py", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/local/lib/python2.7/dist-packages/cffi-0.9.2-py2.7-linux-x86_64.egg/xkcdpass.py", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/local/lib/python2.7/dist-packages/enum34-1.0.4-py2.7.egg/xkcdpass.py", O_RDONLY) = -1 ENOTDIR (Not a directory)
open("/usr/local/lib/python2.7/dist-packages/pyasn1-0.1.7-py2.7.egg/xkcdpass.py", O_RDONLY) = -1 ENOTDIR (Not a directory)
open("/usr/local/lib/python2.7/dist-packages/pycparser-2.10-py2.7.egg/xkcdpass.py", O_RDONLY) = -1 ENOTDIR (Not a directory)
open("/usr/lib/python2.7/dist-packages/xkcdpass.py", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/lib/python2.7/xkcdpass.py", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/lib/python2.7/plat-x86_64-linux-gnu/xkcdpass.py", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/lib/python2.7/lib-tk/xkcdpass.py", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/lib/python2.7/lib-old/xkcdpass.py", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/lib/python2.7/lib-dynload/xkcdpass.py", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/local/lib/python2.7/dist-packages/xkcdpass.py", O_RDONLY) = -1 ENOENT (No such file or directory)
write(2, "ImportError", 11ImportError)             = 11
write(2, ": ", 2: )                       = 2
write(2, "No module named xkcd_password", 29No module named xkcd_password) = 29

**Comment by redacted** [comment] 2015-04-14 08:44
Hi durzo, I can't reproduce this at all on either python2 or python3 on Ubuntu 14.04 LTS. Can you try in the REPL or ipython? Does the command line tool work correctly?

**Comment by redacted** [comment] 2015-06-22 00:58
Closing this for now - reopen if needed.

**Closed by redacted** 2015-06-22 00:58 UTC
